---
- set_fact: kube_apiserver_count="{{ groups['kube-master'] | length }}"
- set_fact: kube_apiserver_address="{{ ip | default(ansible_default_ipv4['address']) }}"
- set_fact: kube_apiserver_access_address="{{ access_ip | default(kube_apiserver_address) }}"
- set_fact: kube_apiserver_insecure_bind_address="{% if kube_apiserver_listen_localhost %}127.0.0.1{% else %}{{ kube_apiserver_address }}{% endif %}"
- set_fact:
    apiserver_access_port: |-
      {% if loadbalancer_apiserver is defined and loadbalancer_apiserver.port is defined %}
      {{ loadbalancer_apiserver.port }}{% else %}{{ kube_apiserver_port }}{% endif %}
- set_fact: kube_apiserver_endpoint="https://{{ apiserver_loadbalancer_domain_name|default(access_ip|default('127.0.0.1')) }}:{{ apiserver_access_port }}"
- set_fact: kube_apiserver_insecure_endpoint="http://{{ access_ip|default('127.0.0.1') }}:{{ kube_apiserver_insecure_port }}"
- set_fact:
    kube_apiserver_access_endpoint: |-
      {% if kube_apiserver_multiaccess %}
      {%   for host in groups['kube-master'] -%}
      https://{{ hostvars[host].kube_apiserver_access_address }}:{{ kube_apiserver_port }}{% if not loop.last %},{% endif %}
      {%-  endfor %}
      {% else %}{{ kube_apiserver_endpoint }}{% endif %}
- set_fact:
    kube_apiserver_insecure_access_endpoint: |-
      {% if kube_apiserver_multiaccess %}
      {%   for host in groups['kube-master'] -%}
      https://{{ hostvars[host].kube_apiserver_address }}:{{ kube_apiserver_insecure_port }}{% if not loop.last %},{% endif %}
      {%-  endfor %}
      {% else %}{{ kube_apiserver_insecure_endpoint  }}{% endif %}
