---
# Enables Internet connectivity from containers
nat_outgoing: true

# Use IP-over-IP encapsulation across hosts
ipip: false

# cloud_provider can only be set to 'gce' or 'aws'
# cloud_provider:

calicoctl_image_repo: calico/ctl
calicoctl_image_tag: "{{ calico_version }}"

calico_node_image_repo: calico/node
calico_node_image_tag: "{{ calico_version }}"

# Set to true if your Hyperkube has all required components to run
# calico. This is required in order to run canalized calico.
use_hyperkube_cni: false

# Set to true if you want your calico cni to overwrite the one from
# hyperkube while leaving cni plugins intact.
overwrite_cni: false
